### ISSUE TITLE
README review

### ISSUE THREAD

**Issue by Soarex16** [winter-yuki/LambdaRPC.kt#36]
tbd

**Comment by Soarex16** [comment]
2 вставка кода
- Надо описать что такое кодер
- Описать выше `j`

3 вставка кода
- непонятно что за функция bf (если не библиотечная, примера ради, то лучше быть более verbose)

Про концепции lib service, преимуществах *можно* (это **не замечание**, а просто как один из возможных вариантов) рассказать до примеров кода. Чтобы как сторителлинг получилось "вот есть сервисы, к ним шлют запросы, больно и грустно, а вот тут ЛИБ СЕРВИСЫ, которые есть суть то-то, умеют это" и потом сразу пример кода.

Раздел λRPC functions тоже можно перенести до примера кода, чтобы погрузить пользователя в концепции

**Comment by penguin-boxx** [comment]
> Раздел λRPC functions тоже можно перенести до примера кода

Это какая-то техническая фигня, боюсь тогда до примера не дочитают :)
